#!/bin/bash

#   ===========================================================================
#       This is the post_push hook script for the base build.
#   ===========================================================================

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)  
repoName=${IMAGE_NAME:0:tagStart-1}

# Get Nextcloud version from official Docker image
export $(docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}' docker pull nodered/node-red-docker | grep NODE_VERSION)
# NEXTCLOUD_VERSION=....

# Split NODE_VERSION for naming the tags
version=( ${NODE_VERSION//./ } )
# TAG naming: version="${version[0]}.${version[1]}.${version[2]}"

# Tag and push image for each additional tag
for tag in {"${NODE_VERSION}","${version[0]}.${version[1]}","${version[0]}",stable,production,latest}; do  
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
