name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file base/Dockerfile --tag nodered-openhab-bool-calc:latest
  
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        workdir: base
        name: majortwip/nodered-openhab-bool-calc
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
